//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.17 at 06:32:45 PM CET 
//


package org.subsonic.restapi;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PodcastStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PodcastStatus">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="new"/>
 *     &lt;enumeration value="downloading"/>
 *     &lt;enumeration value="completed"/>
 *     &lt;enumeration value="error"/>
 *     &lt;enumeration value="deleted"/>
 *     &lt;enumeration value="skipped"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PodcastStatus")
@XmlEnum
public enum PodcastStatus {

    @XmlEnumValue("new")
    NEW("new"),
    @XmlEnumValue("downloading")
    DOWNLOADING("downloading"),
    @XmlEnumValue("completed")
    COMPLETED("completed"),
    @XmlEnumValue("error")
    ERROR("error"),
    @XmlEnumValue("deleted")
    DELETED("deleted"),
    @XmlEnumValue("skipped")
    SKIPPED("skipped");
    private final String value;

    PodcastStatus(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PodcastStatus fromValue(String v) {
        for (PodcastStatus c: PodcastStatus.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
