//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.17 at 06:32:45 PM CET 
//


package org.subsonic.restapi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Response complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Response">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice minOccurs="0">
 *         &lt;element name="musicFolders" type="{http://subsonic.org/restapi}MusicFolders"/>
 *         &lt;element name="indexes" type="{http://subsonic.org/restapi}Indexes"/>
 *         &lt;element name="directory" type="{http://subsonic.org/restapi}Directory"/>
 *         &lt;element name="nowPlaying" type="{http://subsonic.org/restapi}NowPlaying"/>
 *         &lt;element name="searchResult" type="{http://subsonic.org/restapi}SearchResult"/>
 *         &lt;element name="searchResult2" type="{http://subsonic.org/restapi}SearchResult2"/>
 *         &lt;element name="playlists" type="{http://subsonic.org/restapi}Playlists"/>
 *         &lt;element name="playlist" type="{http://subsonic.org/restapi}Playlist"/>
 *         &lt;element name="jukeboxStatus" type="{http://subsonic.org/restapi}JukeboxStatus"/>
 *         &lt;element name="jukeboxPlaylist" type="{http://subsonic.org/restapi}JukeboxPlaylist"/>
 *         &lt;element name="license" type="{http://subsonic.org/restapi}License"/>
 *         &lt;element name="user" type="{http://subsonic.org/restapi}User"/>
 *         &lt;element name="chatMessages" type="{http://subsonic.org/restapi}ChatMessages"/>
 *         &lt;element name="albumList" type="{http://subsonic.org/restapi}AlbumList"/>
 *         &lt;element name="randomSongs" type="{http://subsonic.org/restapi}RandomSongs"/>
 *         &lt;element name="lyrics" type="{http://subsonic.org/restapi}Lyrics"/>
 *         &lt;element name="podcasts" type="{http://subsonic.org/restapi}Podcasts"/>
 *         &lt;element name="shares" type="{http://subsonic.org/restapi}Shares"/>
 *         &lt;element name="error" type="{http://subsonic.org/restapi}Error"/>
 *       &lt;/choice>
 *       &lt;attribute name="status" use="required" type="{http://subsonic.org/restapi}ResponseStatus" />
 *       &lt;attribute name="version" use="required" type="{http://subsonic.org/restapi}Version" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Response", propOrder = {
    "musicFolders",
    "indexes",
    "directory",
    "nowPlaying",
    "searchResult",
    "searchResult2",
    "playlists",
    "playlist",
    "jukeboxStatus",
    "jukeboxPlaylist",
    "license",
    "user",
    "chatMessages",
    "albumList",
    "randomSongs",
    "lyrics",
    "podcasts",
    "shares",
    "error"
})
public class Response {

    protected MusicFolders musicFolders;
    protected Indexes indexes;
    protected Directory directory;
    protected NowPlaying nowPlaying;
    protected SearchResult searchResult;
    protected SearchResult2 searchResult2;
    protected Playlists playlists;
    protected Playlist playlist;
    protected JukeboxStatus jukeboxStatus;
    protected JukeboxPlaylist jukeboxPlaylist;
    protected License license;
    protected User user;
    protected ChatMessages chatMessages;
    protected AlbumList albumList;
    protected RandomSongs randomSongs;
    protected Lyrics lyrics;
    protected Podcasts podcasts;
    protected Shares shares;
    protected Error error;
    @XmlAttribute(required = true)
    protected ResponseStatus status;
    @XmlAttribute(required = true)
    protected String version;

    /**
     * Gets the value of the musicFolders property.
     * 
     * @return
     *     possible object is
     *     {@link MusicFolders }
     *     
     */
    public MusicFolders getMusicFolders() {
        return musicFolders;
    }

    /**
     * Sets the value of the musicFolders property.
     * 
     * @param value
     *     allowed object is
     *     {@link MusicFolders }
     *     
     */
    public void setMusicFolders(MusicFolders value) {
        this.musicFolders = value;
    }

    /**
     * Gets the value of the indexes property.
     * 
     * @return
     *     possible object is
     *     {@link Indexes }
     *     
     */
    public Indexes getIndexes() {
        return indexes;
    }

    /**
     * Sets the value of the indexes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Indexes }
     *     
     */
    public void setIndexes(Indexes value) {
        this.indexes = value;
    }

    /**
     * Gets the value of the directory property.
     * 
     * @return
     *     possible object is
     *     {@link Directory }
     *     
     */
    public Directory getDirectory() {
        return directory;
    }

    /**
     * Sets the value of the directory property.
     * 
     * @param value
     *     allowed object is
     *     {@link Directory }
     *     
     */
    public void setDirectory(Directory value) {
        this.directory = value;
    }

    /**
     * Gets the value of the nowPlaying property.
     * 
     * @return
     *     possible object is
     *     {@link NowPlaying }
     *     
     */
    public NowPlaying getNowPlaying() {
        return nowPlaying;
    }

    /**
     * Sets the value of the nowPlaying property.
     * 
     * @param value
     *     allowed object is
     *     {@link NowPlaying }
     *     
     */
    public void setNowPlaying(NowPlaying value) {
        this.nowPlaying = value;
    }

    /**
     * Gets the value of the searchResult property.
     * 
     * @return
     *     possible object is
     *     {@link SearchResult }
     *     
     */
    public SearchResult getSearchResult() {
        return searchResult;
    }

    /**
     * Sets the value of the searchResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchResult }
     *     
     */
    public void setSearchResult(SearchResult value) {
        this.searchResult = value;
    }

    /**
     * Gets the value of the searchResult2 property.
     * 
     * @return
     *     possible object is
     *     {@link SearchResult2 }
     *     
     */
    public SearchResult2 getSearchResult2() {
        return searchResult2;
    }

    /**
     * Sets the value of the searchResult2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchResult2 }
     *     
     */
    public void setSearchResult2(SearchResult2 value) {
        this.searchResult2 = value;
    }

    /**
     * Gets the value of the playlists property.
     * 
     * @return
     *     possible object is
     *     {@link Playlists }
     *     
     */
    public Playlists getPlaylists() {
        return playlists;
    }

    /**
     * Sets the value of the playlists property.
     * 
     * @param value
     *     allowed object is
     *     {@link Playlists }
     *     
     */
    public void setPlaylists(Playlists value) {
        this.playlists = value;
    }

    /**
     * Gets the value of the playlist property.
     * 
     * @return
     *     possible object is
     *     {@link Playlist }
     *     
     */
    public Playlist getPlaylist() {
        return playlist;
    }

    /**
     * Sets the value of the playlist property.
     * 
     * @param value
     *     allowed object is
     *     {@link Playlist }
     *     
     */
    public void setPlaylist(Playlist value) {
        this.playlist = value;
    }

    /**
     * Gets the value of the jukeboxStatus property.
     * 
     * @return
     *     possible object is
     *     {@link JukeboxStatus }
     *     
     */
    public JukeboxStatus getJukeboxStatus() {
        return jukeboxStatus;
    }

    /**
     * Sets the value of the jukeboxStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link JukeboxStatus }
     *     
     */
    public void setJukeboxStatus(JukeboxStatus value) {
        this.jukeboxStatus = value;
    }

    /**
     * Gets the value of the jukeboxPlaylist property.
     * 
     * @return
     *     possible object is
     *     {@link JukeboxPlaylist }
     *     
     */
    public JukeboxPlaylist getJukeboxPlaylist() {
        return jukeboxPlaylist;
    }

    /**
     * Sets the value of the jukeboxPlaylist property.
     * 
     * @param value
     *     allowed object is
     *     {@link JukeboxPlaylist }
     *     
     */
    public void setJukeboxPlaylist(JukeboxPlaylist value) {
        this.jukeboxPlaylist = value;
    }

    /**
     * Gets the value of the license property.
     * 
     * @return
     *     possible object is
     *     {@link License }
     *     
     */
    public License getLicense() {
        return license;
    }

    /**
     * Sets the value of the license property.
     * 
     * @param value
     *     allowed object is
     *     {@link License }
     *     
     */
    public void setLicense(License value) {
        this.license = value;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link User }
     *     
     */
    public User getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link User }
     *     
     */
    public void setUser(User value) {
        this.user = value;
    }

    /**
     * Gets the value of the chatMessages property.
     * 
     * @return
     *     possible object is
     *     {@link ChatMessages }
     *     
     */
    public ChatMessages getChatMessages() {
        return chatMessages;
    }

    /**
     * Sets the value of the chatMessages property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChatMessages }
     *     
     */
    public void setChatMessages(ChatMessages value) {
        this.chatMessages = value;
    }

    /**
     * Gets the value of the albumList property.
     * 
     * @return
     *     possible object is
     *     {@link AlbumList }
     *     
     */
    public AlbumList getAlbumList() {
        return albumList;
    }

    /**
     * Sets the value of the albumList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlbumList }
     *     
     */
    public void setAlbumList(AlbumList value) {
        this.albumList = value;
    }

    /**
     * Gets the value of the randomSongs property.
     * 
     * @return
     *     possible object is
     *     {@link RandomSongs }
     *     
     */
    public RandomSongs getRandomSongs() {
        return randomSongs;
    }

    /**
     * Sets the value of the randomSongs property.
     * 
     * @param value
     *     allowed object is
     *     {@link RandomSongs }
     *     
     */
    public void setRandomSongs(RandomSongs value) {
        this.randomSongs = value;
    }

    /**
     * Gets the value of the lyrics property.
     * 
     * @return
     *     possible object is
     *     {@link Lyrics }
     *     
     */
    public Lyrics getLyrics() {
        return lyrics;
    }

    /**
     * Sets the value of the lyrics property.
     * 
     * @param value
     *     allowed object is
     *     {@link Lyrics }
     *     
     */
    public void setLyrics(Lyrics value) {
        this.lyrics = value;
    }

    /**
     * Gets the value of the podcasts property.
     * 
     * @return
     *     possible object is
     *     {@link Podcasts }
     *     
     */
    public Podcasts getPodcasts() {
        return podcasts;
    }

    /**
     * Sets the value of the podcasts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Podcasts }
     *     
     */
    public void setPodcasts(Podcasts value) {
        this.podcasts = value;
    }

    /**
     * Gets the value of the shares property.
     * 
     * @return
     *     possible object is
     *     {@link Shares }
     *     
     */
    public Shares getShares() {
        return shares;
    }

    /**
     * Sets the value of the shares property.
     * 
     * @param value
     *     allowed object is
     *     {@link Shares }
     *     
     */
    public void setShares(Shares value) {
        this.shares = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link Error }
     *     
     */
    public Error getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link Error }
     *     
     */
    public void setError(Error value) {
        this.error = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseStatus }
     *     
     */
    public ResponseStatus getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseStatus }
     *     
     */
    public void setStatus(ResponseStatus value) {
        this.status = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
